// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "DWT.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic DWT::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic DWT::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<28> DWT::ap_ST_fsm_state1 = "1";
const sc_lv<28> DWT::ap_ST_fsm_state2 = "10";
const sc_lv<28> DWT::ap_ST_fsm_state3 = "100";
const sc_lv<28> DWT::ap_ST_fsm_state4 = "1000";
const sc_lv<28> DWT::ap_ST_fsm_state5 = "10000";
const sc_lv<28> DWT::ap_ST_fsm_state6 = "100000";
const sc_lv<28> DWT::ap_ST_fsm_state7 = "1000000";
const sc_lv<28> DWT::ap_ST_fsm_state8 = "10000000";
const sc_lv<28> DWT::ap_ST_fsm_state9 = "100000000";
const sc_lv<28> DWT::ap_ST_fsm_state10 = "1000000000";
const sc_lv<28> DWT::ap_ST_fsm_state11 = "10000000000";
const sc_lv<28> DWT::ap_ST_fsm_state12 = "100000000000";
const sc_lv<28> DWT::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<28> DWT::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<28> DWT::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<28> DWT::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<28> DWT::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<28> DWT::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<28> DWT::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<28> DWT::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<28> DWT::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<28> DWT::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<28> DWT::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<28> DWT::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<28> DWT::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<28> DWT::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<28> DWT::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<28> DWT::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<32> DWT::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> DWT::ap_const_lv1_0 = "0";
const sc_lv<32> DWT::ap_const_lv32_1 = "1";
const sc_lv<32> DWT::ap_const_lv32_2 = "10";
const sc_lv<32> DWT::ap_const_lv32_3 = "11";
const sc_lv<32> DWT::ap_const_lv32_4 = "100";
const sc_lv<32> DWT::ap_const_lv32_5 = "101";
const sc_lv<32> DWT::ap_const_lv32_7 = "111";
const sc_lv<1> DWT::ap_const_lv1_1 = "1";
const sc_lv<32> DWT::ap_const_lv32_8 = "1000";
const sc_lv<32> DWT::ap_const_lv32_9 = "1001";
const sc_lv<32> DWT::ap_const_lv32_A = "1010";
const sc_lv<32> DWT::ap_const_lv32_D = "1101";
const sc_lv<32> DWT::ap_const_lv32_11 = "10001";
const sc_lv<32> DWT::ap_const_lv32_13 = "10011";
const sc_lv<32> DWT::ap_const_lv32_15 = "10101";
const sc_lv<32> DWT::ap_const_lv32_16 = "10110";
const sc_lv<32> DWT::ap_const_lv32_18 = "11000";
const sc_lv<32> DWT::ap_const_lv32_19 = "11001";
const sc_lv<32> DWT::ap_const_lv32_1A = "11010";
const sc_lv<11> DWT::ap_const_lv11_0 = "00000000000";
const sc_lv<3> DWT::ap_const_lv3_0 = "000";
const sc_lv<32> DWT::ap_const_lv32_6 = "110";
const sc_lv<32> DWT::ap_const_lv32_400 = "10000000000";
const sc_lv<32> DWT::ap_const_lv32_12 = "10010";
const sc_lv<31> DWT::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<32> DWT::ap_const_lv32_14 = "10100";
const sc_lv<32> DWT::ap_const_lv32_17 = "10111";
const sc_lv<32> DWT::ap_const_lv32_1B = "11011";
const sc_lv<32> DWT::ap_const_lv32_C = "1100";
const sc_lv<32> DWT::ap_const_lv32_E = "1110";
const sc_lv<32> DWT::ap_const_lv32_B = "1011";
const sc_lv<11> DWT::ap_const_lv11_1 = "1";
const sc_lv<11> DWT::ap_const_lv11_7FF = "11111111111";
const sc_lv<3> DWT::ap_const_lv3_1 = "1";
const sc_lv<3> DWT::ap_const_lv3_4 = "100";
const sc_lv<11> DWT::ap_const_lv11_400 = "10000000000";
const sc_lv<3> DWT::ap_const_lv3_5 = "101";
const sc_lv<32> DWT::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<32> DWT::ap_const_lv32_1F = "11111";
const sc_lv<31> DWT::ap_const_lv31_1 = "1";
const sc_lv<22> DWT::ap_const_lv22_1 = "1";
const bool DWT::ap_const_boolean_1 = true;

DWT::DWT(sc_module_name name) : sc_module(name), mVcdFile(0) {
    data_in_U = new DWT_data_in("data_in_U");
    data_in_U->clk(ap_clk);
    data_in_U->reset(ap_rst);
    data_in_U->address0(data_in_address0);
    data_in_U->ce0(data_in_ce0);
    data_in_U->we0(data_in_we0);
    data_in_U->d0(data);
    data_in_U->q0(data_in_q0);
    filter_g_U = new DWT_filter_g("filter_g_U");
    filter_g_U->clk(ap_clk);
    filter_g_U->reset(ap_rst);
    filter_g_U->address0(filter_g_address0);
    filter_g_U->ce0(filter_g_ce0);
    filter_g_U->q0(filter_g_q0);
    filter_h_U = new DWT_filter_h("filter_h_U");
    filter_h_U->clk(ap_clk);
    filter_h_U->reset(ap_rst);
    filter_h_U->address0(filter_h_address0);
    filter_h_U->ce0(filter_h_ce0);
    filter_h_U->q0(filter_h_q0);
    data_input_U = new DWT_data_input("data_input_U");
    data_input_U->clk(ap_clk);
    data_input_U->reset(ap_rst);
    data_input_U->address0(data_input_address0);
    data_input_U->ce0(data_input_ce0);
    data_input_U->we0(data_input_we0);
    data_input_U->d0(data_input_d0);
    data_input_U->q0(data_input_q0);
    data_store_U = new DWT_data_input("data_store_U");
    data_store_U->clk(ap_clk);
    data_store_U->reset(ap_rst);
    data_store_U->address0(data_store_address0);
    data_store_U->ce0(data_store_ce0);
    data_store_U->we0(data_store_we0);
    data_store_U->d0(data_store_d0);
    data_store_U->q0(data_store_q0);
    data_output_U = new DWT_data_output("data_output_U");
    data_output_U->clk(ap_clk);
    data_output_U->reset(ap_rst);
    data_output_U->address0(data_output_address0);
    data_output_U->ce0(data_output_ce0);
    data_output_U->we0(data_output_we0);
    data_output_U->d0(data_output_d0);
    data_output_U->q0(data_output_q0);
    DWT_fadd_32ns_32nbkb_U1 = new DWT_fadd_32ns_32nbkb<1,4,32,32,32>("DWT_fadd_32ns_32nbkb_U1");
    DWT_fadd_32ns_32nbkb_U1->clk(ap_clk);
    DWT_fadd_32ns_32nbkb_U1->reset(ap_rst);
    DWT_fadd_32ns_32nbkb_U1->din0(data_store_load_1_reg_1363);
    DWT_fadd_32ns_32nbkb_U1->din1(tmp_34_reg_1358);
    DWT_fadd_32ns_32nbkb_U1->ce(ap_var_for_const0);
    DWT_fadd_32ns_32nbkb_U1->dout(grp_fu_571_p2);
    DWT_fadd_32ns_32nbkb_U2 = new DWT_fadd_32ns_32nbkb<1,4,32,32,32>("DWT_fadd_32ns_32nbkb_U2");
    DWT_fadd_32ns_32nbkb_U2->clk(ap_clk);
    DWT_fadd_32ns_32nbkb_U2->reset(ap_rst);
    DWT_fadd_32ns_32nbkb_U2->din0(data_output_load_1_reg_1373);
    DWT_fadd_32ns_32nbkb_U2->din1(tmp_37_reg_1368);
    DWT_fadd_32ns_32nbkb_U2->ce(ap_var_for_const0);
    DWT_fadd_32ns_32nbkb_U2->dout(grp_fu_575_p2);
    DWT_fmul_32ns_32ncud_U3 = new DWT_fmul_32ns_32ncud<1,3,32,32,32>("DWT_fmul_32ns_32ncud_U3");
    DWT_fmul_32ns_32ncud_U3->clk(ap_clk);
    DWT_fmul_32ns_32ncud_U3->reset(ap_rst);
    DWT_fmul_32ns_32ncud_U3->din0(data_input_load_reg_1342);
    DWT_fmul_32ns_32ncud_U3->din1(filter_g_load_reg_1348);
    DWT_fmul_32ns_32ncud_U3->ce(ap_var_for_const0);
    DWT_fmul_32ns_32ncud_U3->dout(grp_fu_579_p2);
    DWT_fmul_32ns_32ncud_U4 = new DWT_fmul_32ns_32ncud<1,3,32,32,32>("DWT_fmul_32ns_32ncud_U4");
    DWT_fmul_32ns_32ncud_U4->clk(ap_clk);
    DWT_fmul_32ns_32ncud_U4->reset(ap_rst);
    DWT_fmul_32ns_32ncud_U4->din0(data_input_load_reg_1342);
    DWT_fmul_32ns_32ncud_U4->din1(filter_h_load_reg_1353);
    DWT_fmul_32ns_32ncud_U4->ce(ap_var_for_const0);
    DWT_fmul_32ns_32ncud_U4->dout(grp_fu_583_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_condition_178);
    sensitive << ( cal_flag_load_reg_1170 );
    sensitive << ( exitcond4_fu_730_p2 );
    sensitive << ( tmp_11_fu_800_p2 );
    sensitive << ( tmp_13_fu_810_p2 );

    SC_METHOD(thread_ap_condition_453);
    sensitive << ( cal_flag_load_reg_1170 );
    sensitive << ( exitcond4_fu_730_p2 );
    sensitive << ( tmp_11_fu_800_p2 );
    sensitive << ( tmp_13_fu_810_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state28 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_cnt_loc_i_phi_fu_381_p4);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cnt );
    sensitive << ( cal_flag_load_load_fu_587_p1 );
    sensitive << ( tmp_1_i_fu_602_p2 );
    sensitive << ( tmp_i_fu_591_p2 );

    SC_METHOD(thread_ap_phi_mux_read_ready_i_phi_fu_390_p4);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cal_flag_load_load_fu_587_p1 );
    sensitive << ( tmp_i_fu_591_p2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state28 );

    SC_METHOD(thread_cal_flag_load_load_fu_587_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cal_flag );

    SC_METHOD(thread_data_in_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_3_fu_725_p1 );
    sensitive << ( tmp_2_i_fu_615_p1 );

    SC_METHOD(thread_data_in_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_data_in_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cal_flag_load_load_fu_587_p1 );
    sensitive << ( tmp_i_fu_591_p2 );

    SC_METHOD(thread_data_input_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_3_reg_1221 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_1_fu_702_p1 );
    sensitive << ( tmp_32_fu_948_p1 );
    sensitive << ( tmp_27_fu_996_p1 );
    sensitive << ( tmp_36_fu_1017_p1 );

    SC_METHOD(thread_data_input_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_data_input_d0);
    sensitive << ( data_in_q0 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( data_store_q0 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_data_input_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( icmp_fu_1011_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_data_out);
    sensitive << ( cal_flag_load_reg_1170 );
    sensitive << ( tmp_3_i_reg_1177 );
    sensitive << ( tmp_11_reg_1262 );
    sensitive << ( data_output_q0 );
    sensitive << ( ap_CS_fsm_state28 );

    SC_METHOD(thread_data_out_ap_vld);
    sensitive << ( cal_flag_load_reg_1170 );
    sensitive << ( tmp_3_i_reg_1177 );
    sensitive << ( tmp_11_reg_1262 );
    sensitive << ( ap_CS_fsm_state28 );

    SC_METHOD(thread_data_output_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( data_output_addr_1_reg_1293 );
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( tmp_7_fu_679_p1 );
    sensitive << ( tmp_59_cast_fu_1060_p1 );
    sensitive << ( tmp_60_cast_fu_1073_p1 );
    sensitive << ( tmp_61_cast_fu_1103_p1 );
    sensitive << ( tmp_57_cast_fu_1153_p1 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_data_output_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_data_output_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( data_output_q0 );
    sensitive << ( tmp_38_reg_1383 );
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_data_output_we0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( icmp5_fu_1088_p2 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_data_store_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( data_store_addr_1_reg_1298 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( tmp_5_fu_648_p1 );
    sensitive << ( tmp_26_fu_991_p1 );
    sensitive << ( tmp_48_fu_1126_p1 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_data_store_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_data_store_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_35_reg_1378 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_data_store_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( exitcond3_fu_1114_p2 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_exitcond3_fu_1114_p2);
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( i6_reg_540 );

    SC_METHOD(thread_exitcond4_fu_730_p2);
    sensitive << ( cal_flag_load_reg_1170 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( level_reg_454 );

    SC_METHOD(thread_exitcond5_fu_713_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( i1_reg_443 );

    SC_METHOD(thread_filter_g_address0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_58_cast_fu_962_p1 );

    SC_METHOD(thread_filter_g_ce0);
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_filter_h_address0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_58_cast_fu_962_p1 );

    SC_METHOD(thread_filter_h_ce0);
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_i2_cast_fu_968_p1);
    sensitive << ( i2_reg_499 );

    SC_METHOD(thread_i4_cast_fu_1028_p1);
    sensitive << ( i4_reg_520 );

    SC_METHOD(thread_i_1_fu_719_p2);
    sensitive << ( i1_reg_443 );

    SC_METHOD(thread_i_2_fu_977_p2);
    sensitive << ( i2_reg_499 );

    SC_METHOD(thread_i_3_fu_1022_p2);
    sensitive << ( i3_reg_511 );

    SC_METHOD(thread_i_4_fu_1037_p2);
    sensitive << ( i4_reg_520 );

    SC_METHOD(thread_i_5_fu_1108_p2);
    sensitive << ( i5_reg_531 );

    SC_METHOD(thread_i_6_fu_1120_p2);
    sensitive << ( i6_reg_540 );

    SC_METHOD(thread_i_7_fu_912_p3);
    sensitive << ( tmp_20_fu_864_p3 );
    sensitive << ( p_neg_t_fu_892_p2 );
    sensitive << ( tmp_33_fu_908_p1 );

    SC_METHOD(thread_icmp5_fu_1088_p2);
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( tmp_57_fu_1078_p4 );

    SC_METHOD(thread_icmp_fu_1011_p2);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( tmp_50_fu_1001_p4 );

    SC_METHOD(thread_indvarinc1_fu_659_p2);
    sensitive << ( invdar1_reg_409 );

    SC_METHOD(thread_indvarinc2_fu_665_p2);
    sensitive << ( invdar2_reg_421 );

    SC_METHOD(thread_indvarinc3_fu_696_p2);
    sensitive << ( invdar3_reg_432 );

    SC_METHOD(thread_indvarinc_fu_642_p2);
    sensitive << ( invdar_reg_398 );

    SC_METHOD(thread_k_1_fu_931_p2);
    sensitive << ( k_reg_488 );

    SC_METHOD(thread_level_1_fu_736_p2);
    sensitive << ( level_reg_454 );

    SC_METHOD(thread_n_1_fu_833_p2);
    sensitive << ( n_reg_477 );

    SC_METHOD(thread_p_lshr_f_fu_898_p4);
    sensitive << ( cal_length_reg_465 );

    SC_METHOD(thread_p_lshr_fu_878_p4);
    sensitive << ( p_neg_fu_872_p2 );

    SC_METHOD(thread_p_neg_fu_872_p2);
    sensitive << ( cal_length_reg_465 );

    SC_METHOD(thread_p_neg_t_fu_892_p2);
    sensitive << ( tmp_30_fu_888_p1 );

    SC_METHOD(thread_p_shl1_cast_fu_768_p1);
    sensitive << ( tmp_10_fu_760_p3 );

    SC_METHOD(thread_p_shl_cast_fu_756_p1);
    sensitive << ( tmp_8_fu_748_p3 );

    SC_METHOD(thread_read_over);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cal_flag_load_load_fu_587_p1 );
    sensitive << ( tmp_3_i_fu_620_p2 );

    SC_METHOD(thread_read_over_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cal_flag_load_load_fu_587_p1 );

    SC_METHOD(thread_read_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cal_flag_load_load_fu_587_p1 );
    sensitive << ( read_ready_write_ass_fu_626_p2 );

    SC_METHOD(thread_read_ready_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cal_flag_load_load_fu_587_p1 );

    SC_METHOD(thread_read_ready_write_ass_fu_626_p2);
    sensitive << ( tmp_3_i_fu_620_p2 );
    sensitive << ( ap_phi_mux_read_ready_i_phi_fu_390_p4 );

    SC_METHOD(thread_tmp_10_fu_760_p3);
    sensitive << ( level_reg_454 );

    SC_METHOD(thread_tmp_11_fu_800_p2);
    sensitive << ( i );
    sensitive << ( cal_flag_load_reg_1170 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond4_fu_730_p2 );

    SC_METHOD(thread_tmp_12_fu_828_p2);
    sensitive << ( tmp_4_reg_1239 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( n_reg_477 );

    SC_METHOD(thread_tmp_13_fu_810_p2);
    sensitive << ( j );
    sensitive << ( cal_flag_load_reg_1170 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond4_fu_730_p2 );
    sensitive << ( tmp_11_fu_800_p2 );

    SC_METHOD(thread_tmp_14_fu_920_p2);
    sensitive << ( i_7_fu_912_p3 );

    SC_METHOD(thread_tmp_16_fu_772_p2);
    sensitive << ( p_shl1_cast_fu_768_p1 );
    sensitive << ( p_shl_cast_fu_756_p1 );

    SC_METHOD(thread_tmp_17_fu_845_p1);
    sensitive << ( n_reg_477 );

    SC_METHOD(thread_tmp_18_fu_816_p2);
    sensitive << ( i );

    SC_METHOD(thread_tmp_19_fu_778_p3);
    sensitive << ( level_reg_454 );

    SC_METHOD(thread_tmp_1_fu_702_p1);
    sensitive << ( invdar3_reg_432 );

    SC_METHOD(thread_tmp_1_i_fu_602_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cnt );

    SC_METHOD(thread_tmp_1_i_fu_602_p2);
    sensitive << ( tmp_1_i_fu_602_p0 );

    SC_METHOD(thread_tmp_20_fu_864_p3);
    sensitive << ( cal_length_reg_465 );

    SC_METHOD(thread_tmp_21_fu_1158_p2);
    sensitive << ( j_load_2_reg_560 );

    SC_METHOD(thread_tmp_22_fu_972_p2);
    sensitive << ( tmp_14_reg_1310 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( i2_cast_fu_968_p1 );

    SC_METHOD(thread_tmp_23_fu_926_p2);
    sensitive << ( tmp_42_reg_1287 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( k_reg_488 );

    SC_METHOD(thread_tmp_25_fu_983_p3);
    sensitive << ( i2_reg_499 );

    SC_METHOD(thread_tmp_26_fu_991_p1);
    sensitive << ( tmp_25_fu_983_p3 );

    SC_METHOD(thread_tmp_27_fu_996_p1);
    sensitive << ( i2_reg_499 );

    SC_METHOD(thread_tmp_29_fu_937_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_23_fu_926_p2 );
    sensitive << ( k_reg_488 );

    SC_METHOD(thread_tmp_2_fu_707_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( invdar3_reg_432 );

    SC_METHOD(thread_tmp_2_i_fu_615_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cnt );

    SC_METHOD(thread_tmp_2_i_fu_615_p1);
    sensitive << ( tmp_2_i_fu_615_p0 );

    SC_METHOD(thread_tmp_30_fu_888_p1);
    sensitive << ( p_lshr_fu_878_p4 );

    SC_METHOD(thread_tmp_31_fu_943_p2);
    sensitive << ( tmp_42_reg_1287 );
    sensitive << ( k_reg_488 );

    SC_METHOD(thread_tmp_32_fu_948_p1);
    sensitive << ( tmp_31_fu_943_p2 );

    SC_METHOD(thread_tmp_33_fu_908_p1);
    sensitive << ( p_lshr_f_fu_898_p4 );

    SC_METHOD(thread_tmp_36_fu_1017_p1);
    sensitive << ( i3_reg_511 );

    SC_METHOD(thread_tmp_3_fu_725_p1);
    sensitive << ( i1_reg_443 );

    SC_METHOD(thread_tmp_3_i_fu_620_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cal_flag_load_load_fu_587_p1 );
    sensitive << ( ap_phi_mux_cnt_loc_i_phi_fu_381_p4 );

    SC_METHOD(thread_tmp_40_fu_1032_p2);
    sensitive << ( tmp_14_reg_1310 );
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( i4_cast_fu_1028_p1 );

    SC_METHOD(thread_tmp_42_fu_839_p2);
    sensitive << ( n_reg_477 );

    SC_METHOD(thread_tmp_43_cast_fu_1047_p3);
    sensitive << ( tmp_53_fu_1043_p1 );

    SC_METHOD(thread_tmp_43_fu_850_p1);
    sensitive << ( n_reg_477 );

    SC_METHOD(thread_tmp_44_fu_854_p2);
    sensitive << ( tmp_50_cast_reg_1249 );
    sensitive << ( tmp_43_fu_850_p1 );

    SC_METHOD(thread_tmp_45_fu_1131_p1);
    sensitive << ( j_load_2_reg_560 );

    SC_METHOD(thread_tmp_47_fu_1135_p1);
    sensitive << ( i_load_1_reg_551 );

    SC_METHOD(thread_tmp_48_fu_1126_p1);
    sensitive << ( i6_reg_540 );

    SC_METHOD(thread_tmp_49_fu_1147_p2);
    sensitive << ( tmp_56_cast_fu_1139_p3 );
    sensitive << ( tmp_45_fu_1131_p1 );

    SC_METHOD(thread_tmp_4_fu_742_p2);
    sensitive << ( cal_length_reg_465 );

    SC_METHOD(thread_tmp_50_cast_fu_786_p1);
    sensitive << ( tmp_19_fu_778_p3 );

    SC_METHOD(thread_tmp_50_fu_1001_p4);
    sensitive << ( i3_reg_511 );

    SC_METHOD(thread_tmp_51_fu_953_p1);
    sensitive << ( k_reg_488 );

    SC_METHOD(thread_tmp_52_fu_957_p2);
    sensitive << ( tmp_16_reg_1244 );
    sensitive << ( tmp_51_fu_953_p1 );

    SC_METHOD(thread_tmp_53_fu_1043_p1);
    sensitive << ( i4_reg_520 );

    SC_METHOD(thread_tmp_54_cast_fu_859_p1);
    sensitive << ( tmp_44_fu_854_p2 );

    SC_METHOD(thread_tmp_54_fu_1055_p2);
    sensitive << ( tmp_50_cast_reg_1249 );
    sensitive << ( tmp_43_cast_fu_1047_p3 );

    SC_METHOD(thread_tmp_55_fu_1065_p1);
    sensitive << ( i4_reg_520 );

    SC_METHOD(thread_tmp_56_cast_fu_1139_p3);
    sensitive << ( tmp_47_fu_1135_p1 );

    SC_METHOD(thread_tmp_56_fu_1069_p2);
    sensitive << ( tmp_50_cast_reg_1249 );
    sensitive << ( tmp_55_reg_1422 );

    SC_METHOD(thread_tmp_57_cast_fu_1153_p1);
    sensitive << ( tmp_49_fu_1147_p2 );

    SC_METHOD(thread_tmp_57_fu_1078_p4);
    sensitive << ( i5_reg_531 );

    SC_METHOD(thread_tmp_58_cast_fu_962_p1);
    sensitive << ( tmp_52_fu_957_p2 );

    SC_METHOD(thread_tmp_58_fu_1094_p1);
    sensitive << ( i5_reg_531 );

    SC_METHOD(thread_tmp_59_cast_fu_1060_p1);
    sensitive << ( tmp_54_fu_1055_p2 );

    SC_METHOD(thread_tmp_59_fu_1098_p2);
    sensitive << ( tmp_50_cast_reg_1249 );
    sensitive << ( tmp_58_fu_1094_p1 );

    SC_METHOD(thread_tmp_5_fu_648_p1);
    sensitive << ( invdar_reg_398 );

    SC_METHOD(thread_tmp_60_cast_fu_1073_p1);
    sensitive << ( tmp_56_fu_1069_p2 );

    SC_METHOD(thread_tmp_61_cast_fu_1103_p1);
    sensitive << ( tmp_59_fu_1098_p2 );

    SC_METHOD(thread_tmp_6_fu_653_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( invdar_reg_398 );

    SC_METHOD(thread_tmp_7_fu_679_p1);
    sensitive << ( tmp_fu_671_p3 );

    SC_METHOD(thread_tmp_8_fu_748_p3);
    sensitive << ( level_reg_454 );

    SC_METHOD(thread_tmp_9_fu_684_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( invdar2_reg_421 );

    SC_METHOD(thread_tmp_fu_671_p3);
    sensitive << ( invdar1_reg_409 );
    sensitive << ( invdar2_reg_421 );

    SC_METHOD(thread_tmp_i_fu_591_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( read_valid );
    sensitive << ( cal_flag_load_load_fu_587_p1 );

    SC_METHOD(thread_tmp_s_fu_690_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( invdar1_reg_409 );
    sensitive << ( tmp_9_fu_684_p2 );

    SC_METHOD(thread_write_valid);
    sensitive << ( cal_flag_load_reg_1170 );
    sensitive << ( tmp_3_i_reg_1177 );
    sensitive << ( tmp_11_reg_1262 );
    sensitive << ( ap_CS_fsm_state28 );

    SC_METHOD(thread_write_valid_ap_vld);
    sensitive << ( cal_flag_load_reg_1170 );
    sensitive << ( tmp_3_i_reg_1177 );
    sensitive << ( tmp_11_reg_1262 );
    sensitive << ( ap_CS_fsm_state28 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cal_flag_load_load_fu_587_p1 );
    sensitive << ( cal_flag_load_reg_1170 );
    sensitive << ( tmp_3_i_fu_620_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( exitcond5_fu_713_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond4_fu_730_p2 );
    sensitive << ( tmp_11_fu_800_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_12_fu_828_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_23_fu_926_p2 );
    sensitive << ( tmp_29_fu_937_p2 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( tmp_22_fu_972_p2 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( icmp_fu_1011_p2 );
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( tmp_40_fu_1032_p2 );
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( icmp5_fu_1088_p2 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( tmp_6_fu_653_p2 );
    sensitive << ( tmp_9_fu_684_p2 );
    sensitive << ( tmp_s_fu_690_p2 );
    sensitive << ( tmp_2_fu_707_p2 );
    sensitive << ( exitcond3_fu_1114_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000000000000000000000000001";
    cal_flag = "0";
    cnt = "00000000000000000000000000000000";
    i = "00000000000000000000000000000000";
    j = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "DWT_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_out, "(port)data_out");
    sc_trace(mVcdFile, data_out_ap_vld, "(port)data_out_ap_vld");
    sc_trace(mVcdFile, data, "(port)data");
    sc_trace(mVcdFile, read_valid, "(port)read_valid");
    sc_trace(mVcdFile, read_ready, "(port)read_ready");
    sc_trace(mVcdFile, read_ready_ap_vld, "(port)read_ready_ap_vld");
    sc_trace(mVcdFile, read_over, "(port)read_over");
    sc_trace(mVcdFile, read_over_ap_vld, "(port)read_over_ap_vld");
    sc_trace(mVcdFile, write_valid, "(port)write_valid");
    sc_trace(mVcdFile, write_valid_ap_vld, "(port)write_valid_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, cal_flag, "cal_flag");
    sc_trace(mVcdFile, cnt, "cnt");
    sc_trace(mVcdFile, data_in_address0, "data_in_address0");
    sc_trace(mVcdFile, data_in_ce0, "data_in_ce0");
    sc_trace(mVcdFile, data_in_we0, "data_in_we0");
    sc_trace(mVcdFile, data_in_q0, "data_in_q0");
    sc_trace(mVcdFile, filter_g_address0, "filter_g_address0");
    sc_trace(mVcdFile, filter_g_ce0, "filter_g_ce0");
    sc_trace(mVcdFile, filter_g_q0, "filter_g_q0");
    sc_trace(mVcdFile, filter_h_address0, "filter_h_address0");
    sc_trace(mVcdFile, filter_h_ce0, "filter_h_ce0");
    sc_trace(mVcdFile, filter_h_q0, "filter_h_q0");
    sc_trace(mVcdFile, i, "i");
    sc_trace(mVcdFile, j, "j");
    sc_trace(mVcdFile, cal_flag_load_load_fu_587_p1, "cal_flag_load_load_fu_587_p1");
    sc_trace(mVcdFile, cal_flag_load_reg_1170, "cal_flag_load_reg_1170");
    sc_trace(mVcdFile, tmp_3_i_fu_620_p2, "tmp_3_i_fu_620_p2");
    sc_trace(mVcdFile, tmp_3_i_reg_1177, "tmp_3_i_reg_1177");
    sc_trace(mVcdFile, indvarinc_fu_642_p2, "indvarinc_fu_642_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, indvarinc1_fu_659_p2, "indvarinc1_fu_659_p2");
    sc_trace(mVcdFile, indvarinc1_reg_1189, "indvarinc1_reg_1189");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, indvarinc2_fu_665_p2, "indvarinc2_fu_665_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, indvarinc3_fu_696_p2, "indvarinc3_fu_696_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, i_1_fu_719_p2, "i_1_fu_719_p2");
    sc_trace(mVcdFile, i_1_reg_1216, "i_1_reg_1216");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_3_fu_725_p1, "tmp_3_fu_725_p1");
    sc_trace(mVcdFile, tmp_3_reg_1221, "tmp_3_reg_1221");
    sc_trace(mVcdFile, exitcond5_fu_713_p2, "exitcond5_fu_713_p2");
    sc_trace(mVcdFile, level_1_fu_736_p2, "level_1_fu_736_p2");
    sc_trace(mVcdFile, level_1_reg_1234, "level_1_reg_1234");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, tmp_4_fu_742_p2, "tmp_4_fu_742_p2");
    sc_trace(mVcdFile, tmp_4_reg_1239, "tmp_4_reg_1239");
    sc_trace(mVcdFile, exitcond4_fu_730_p2, "exitcond4_fu_730_p2");
    sc_trace(mVcdFile, tmp_16_fu_772_p2, "tmp_16_fu_772_p2");
    sc_trace(mVcdFile, tmp_16_reg_1244, "tmp_16_reg_1244");
    sc_trace(mVcdFile, tmp_50_cast_fu_786_p1, "tmp_50_cast_fu_786_p1");
    sc_trace(mVcdFile, tmp_50_cast_reg_1249, "tmp_50_cast_reg_1249");
    sc_trace(mVcdFile, tmp_11_fu_800_p2, "tmp_11_fu_800_p2");
    sc_trace(mVcdFile, tmp_11_reg_1262, "tmp_11_reg_1262");
    sc_trace(mVcdFile, tmp_18_fu_816_p2, "tmp_18_fu_816_p2");
    sc_trace(mVcdFile, tmp_13_fu_810_p2, "tmp_13_fu_810_p2");
    sc_trace(mVcdFile, n_1_fu_833_p2, "n_1_fu_833_p2");
    sc_trace(mVcdFile, n_1_reg_1282, "n_1_reg_1282");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, tmp_42_fu_839_p2, "tmp_42_fu_839_p2");
    sc_trace(mVcdFile, tmp_42_reg_1287, "tmp_42_reg_1287");
    sc_trace(mVcdFile, tmp_12_fu_828_p2, "tmp_12_fu_828_p2");
    sc_trace(mVcdFile, data_output_addr_1_reg_1293, "data_output_addr_1_reg_1293");
    sc_trace(mVcdFile, data_store_addr_1_reg_1298, "data_store_addr_1_reg_1298");
    sc_trace(mVcdFile, i_7_fu_912_p3, "i_7_fu_912_p3");
    sc_trace(mVcdFile, i_7_reg_1303, "i_7_reg_1303");
    sc_trace(mVcdFile, tmp_14_fu_920_p2, "tmp_14_fu_920_p2");
    sc_trace(mVcdFile, tmp_14_reg_1310, "tmp_14_reg_1310");
    sc_trace(mVcdFile, k_1_fu_931_p2, "k_1_fu_931_p2");
    sc_trace(mVcdFile, k_1_reg_1319, "k_1_reg_1319");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, tmp_23_fu_926_p2, "tmp_23_fu_926_p2");
    sc_trace(mVcdFile, tmp_29_fu_937_p2, "tmp_29_fu_937_p2");
    sc_trace(mVcdFile, data_input_q0, "data_input_q0");
    sc_trace(mVcdFile, data_input_load_reg_1342, "data_input_load_reg_1342");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, filter_g_load_reg_1348, "filter_g_load_reg_1348");
    sc_trace(mVcdFile, filter_h_load_reg_1353, "filter_h_load_reg_1353");
    sc_trace(mVcdFile, grp_fu_579_p2, "grp_fu_579_p2");
    sc_trace(mVcdFile, tmp_34_reg_1358, "tmp_34_reg_1358");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, data_store_q0, "data_store_q0");
    sc_trace(mVcdFile, data_store_load_1_reg_1363, "data_store_load_1_reg_1363");
    sc_trace(mVcdFile, grp_fu_583_p2, "grp_fu_583_p2");
    sc_trace(mVcdFile, tmp_37_reg_1368, "tmp_37_reg_1368");
    sc_trace(mVcdFile, data_output_q0, "data_output_q0");
    sc_trace(mVcdFile, data_output_load_1_reg_1373, "data_output_load_1_reg_1373");
    sc_trace(mVcdFile, grp_fu_571_p2, "grp_fu_571_p2");
    sc_trace(mVcdFile, tmp_35_reg_1378, "tmp_35_reg_1378");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, grp_fu_575_p2, "grp_fu_575_p2");
    sc_trace(mVcdFile, tmp_38_reg_1383, "tmp_38_reg_1383");
    sc_trace(mVcdFile, i_2_fu_977_p2, "i_2_fu_977_p2");
    sc_trace(mVcdFile, i_2_reg_1391, "i_2_reg_1391");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, tmp_22_fu_972_p2, "tmp_22_fu_972_p2");
    sc_trace(mVcdFile, i_3_fu_1022_p2, "i_3_fu_1022_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, icmp_fu_1011_p2, "icmp_fu_1011_p2");
    sc_trace(mVcdFile, i_4_fu_1037_p2, "i_4_fu_1037_p2");
    sc_trace(mVcdFile, i_4_reg_1412, "i_4_reg_1412");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, tmp_40_fu_1032_p2, "tmp_40_fu_1032_p2");
    sc_trace(mVcdFile, tmp_55_fu_1065_p1, "tmp_55_fu_1065_p1");
    sc_trace(mVcdFile, tmp_55_reg_1422, "tmp_55_reg_1422");
    sc_trace(mVcdFile, i_5_fu_1108_p2, "i_5_fu_1108_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, icmp5_fu_1088_p2, "icmp5_fu_1088_p2");
    sc_trace(mVcdFile, i_6_fu_1120_p2, "i_6_fu_1120_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, ap_CS_fsm_state27, "ap_CS_fsm_state27");
    sc_trace(mVcdFile, data_input_address0, "data_input_address0");
    sc_trace(mVcdFile, data_input_ce0, "data_input_ce0");
    sc_trace(mVcdFile, data_input_we0, "data_input_we0");
    sc_trace(mVcdFile, data_input_d0, "data_input_d0");
    sc_trace(mVcdFile, data_store_address0, "data_store_address0");
    sc_trace(mVcdFile, data_store_ce0, "data_store_ce0");
    sc_trace(mVcdFile, data_store_we0, "data_store_we0");
    sc_trace(mVcdFile, data_store_d0, "data_store_d0");
    sc_trace(mVcdFile, data_output_address0, "data_output_address0");
    sc_trace(mVcdFile, data_output_ce0, "data_output_ce0");
    sc_trace(mVcdFile, data_output_we0, "data_output_we0");
    sc_trace(mVcdFile, data_output_d0, "data_output_d0");
    sc_trace(mVcdFile, tmp_1_i_fu_602_p2, "tmp_1_i_fu_602_p2");
    sc_trace(mVcdFile, ap_phi_mux_cnt_loc_i_phi_fu_381_p4, "ap_phi_mux_cnt_loc_i_phi_fu_381_p4");
    sc_trace(mVcdFile, tmp_i_fu_591_p2, "tmp_i_fu_591_p2");
    sc_trace(mVcdFile, ap_phi_mux_read_ready_i_phi_fu_390_p4, "ap_phi_mux_read_ready_i_phi_fu_390_p4");
    sc_trace(mVcdFile, invdar_reg_398, "invdar_reg_398");
    sc_trace(mVcdFile, tmp_6_fu_653_p2, "tmp_6_fu_653_p2");
    sc_trace(mVcdFile, invdar1_reg_409, "invdar1_reg_409");
    sc_trace(mVcdFile, tmp_9_fu_684_p2, "tmp_9_fu_684_p2");
    sc_trace(mVcdFile, tmp_s_fu_690_p2, "tmp_s_fu_690_p2");
    sc_trace(mVcdFile, invdar2_reg_421, "invdar2_reg_421");
    sc_trace(mVcdFile, invdar3_reg_432, "invdar3_reg_432");
    sc_trace(mVcdFile, tmp_2_fu_707_p2, "tmp_2_fu_707_p2");
    sc_trace(mVcdFile, i1_reg_443, "i1_reg_443");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, level_reg_454, "level_reg_454");
    sc_trace(mVcdFile, exitcond3_fu_1114_p2, "exitcond3_fu_1114_p2");
    sc_trace(mVcdFile, cal_length_reg_465, "cal_length_reg_465");
    sc_trace(mVcdFile, n_reg_477, "n_reg_477");
    sc_trace(mVcdFile, k_reg_488, "k_reg_488");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, i2_reg_499, "i2_reg_499");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, i3_reg_511, "i3_reg_511");
    sc_trace(mVcdFile, i4_reg_520, "i4_reg_520");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, i5_reg_531, "i5_reg_531");
    sc_trace(mVcdFile, i6_reg_540, "i6_reg_540");
    sc_trace(mVcdFile, i_load_1_reg_551, "i_load_1_reg_551");
    sc_trace(mVcdFile, j_load_2_reg_560, "j_load_2_reg_560");
    sc_trace(mVcdFile, tmp_2_i_fu_615_p1, "tmp_2_i_fu_615_p1");
    sc_trace(mVcdFile, tmp_5_fu_648_p1, "tmp_5_fu_648_p1");
    sc_trace(mVcdFile, tmp_7_fu_679_p1, "tmp_7_fu_679_p1");
    sc_trace(mVcdFile, tmp_1_fu_702_p1, "tmp_1_fu_702_p1");
    sc_trace(mVcdFile, tmp_54_cast_fu_859_p1, "tmp_54_cast_fu_859_p1");
    sc_trace(mVcdFile, tmp_17_fu_845_p1, "tmp_17_fu_845_p1");
    sc_trace(mVcdFile, tmp_32_fu_948_p1, "tmp_32_fu_948_p1");
    sc_trace(mVcdFile, tmp_58_cast_fu_962_p1, "tmp_58_cast_fu_962_p1");
    sc_trace(mVcdFile, tmp_26_fu_991_p1, "tmp_26_fu_991_p1");
    sc_trace(mVcdFile, tmp_27_fu_996_p1, "tmp_27_fu_996_p1");
    sc_trace(mVcdFile, tmp_36_fu_1017_p1, "tmp_36_fu_1017_p1");
    sc_trace(mVcdFile, tmp_59_cast_fu_1060_p1, "tmp_59_cast_fu_1060_p1");
    sc_trace(mVcdFile, tmp_60_cast_fu_1073_p1, "tmp_60_cast_fu_1073_p1");
    sc_trace(mVcdFile, tmp_61_cast_fu_1103_p1, "tmp_61_cast_fu_1103_p1");
    sc_trace(mVcdFile, tmp_48_fu_1126_p1, "tmp_48_fu_1126_p1");
    sc_trace(mVcdFile, tmp_57_cast_fu_1153_p1, "tmp_57_cast_fu_1153_p1");
    sc_trace(mVcdFile, tmp_21_fu_1158_p2, "tmp_21_fu_1158_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state28, "ap_CS_fsm_state28");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, tmp_1_i_fu_602_p0, "tmp_1_i_fu_602_p0");
    sc_trace(mVcdFile, tmp_2_i_fu_615_p0, "tmp_2_i_fu_615_p0");
    sc_trace(mVcdFile, read_ready_write_ass_fu_626_p2, "read_ready_write_ass_fu_626_p2");
    sc_trace(mVcdFile, tmp_fu_671_p3, "tmp_fu_671_p3");
    sc_trace(mVcdFile, tmp_8_fu_748_p3, "tmp_8_fu_748_p3");
    sc_trace(mVcdFile, tmp_10_fu_760_p3, "tmp_10_fu_760_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_768_p1, "p_shl1_cast_fu_768_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_756_p1, "p_shl_cast_fu_756_p1");
    sc_trace(mVcdFile, tmp_19_fu_778_p3, "tmp_19_fu_778_p3");
    sc_trace(mVcdFile, tmp_43_fu_850_p1, "tmp_43_fu_850_p1");
    sc_trace(mVcdFile, tmp_44_fu_854_p2, "tmp_44_fu_854_p2");
    sc_trace(mVcdFile, p_neg_fu_872_p2, "p_neg_fu_872_p2");
    sc_trace(mVcdFile, p_lshr_fu_878_p4, "p_lshr_fu_878_p4");
    sc_trace(mVcdFile, tmp_30_fu_888_p1, "tmp_30_fu_888_p1");
    sc_trace(mVcdFile, p_lshr_f_fu_898_p4, "p_lshr_f_fu_898_p4");
    sc_trace(mVcdFile, tmp_20_fu_864_p3, "tmp_20_fu_864_p3");
    sc_trace(mVcdFile, p_neg_t_fu_892_p2, "p_neg_t_fu_892_p2");
    sc_trace(mVcdFile, tmp_33_fu_908_p1, "tmp_33_fu_908_p1");
    sc_trace(mVcdFile, tmp_31_fu_943_p2, "tmp_31_fu_943_p2");
    sc_trace(mVcdFile, tmp_51_fu_953_p1, "tmp_51_fu_953_p1");
    sc_trace(mVcdFile, tmp_52_fu_957_p2, "tmp_52_fu_957_p2");
    sc_trace(mVcdFile, i2_cast_fu_968_p1, "i2_cast_fu_968_p1");
    sc_trace(mVcdFile, tmp_25_fu_983_p3, "tmp_25_fu_983_p3");
    sc_trace(mVcdFile, tmp_50_fu_1001_p4, "tmp_50_fu_1001_p4");
    sc_trace(mVcdFile, i4_cast_fu_1028_p1, "i4_cast_fu_1028_p1");
    sc_trace(mVcdFile, tmp_53_fu_1043_p1, "tmp_53_fu_1043_p1");
    sc_trace(mVcdFile, tmp_43_cast_fu_1047_p3, "tmp_43_cast_fu_1047_p3");
    sc_trace(mVcdFile, tmp_54_fu_1055_p2, "tmp_54_fu_1055_p2");
    sc_trace(mVcdFile, tmp_56_fu_1069_p2, "tmp_56_fu_1069_p2");
    sc_trace(mVcdFile, tmp_57_fu_1078_p4, "tmp_57_fu_1078_p4");
    sc_trace(mVcdFile, tmp_58_fu_1094_p1, "tmp_58_fu_1094_p1");
    sc_trace(mVcdFile, tmp_59_fu_1098_p2, "tmp_59_fu_1098_p2");
    sc_trace(mVcdFile, tmp_47_fu_1135_p1, "tmp_47_fu_1135_p1");
    sc_trace(mVcdFile, tmp_56_cast_fu_1139_p3, "tmp_56_cast_fu_1139_p3");
    sc_trace(mVcdFile, tmp_45_fu_1131_p1, "tmp_45_fu_1131_p1");
    sc_trace(mVcdFile, tmp_49_fu_1147_p2, "tmp_49_fu_1147_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_condition_178, "ap_condition_178");
    sc_trace(mVcdFile, ap_condition_453, "ap_condition_453");
#endif

    }
    mHdltvinHandle.open("DWT.hdltvin.dat");
    mHdltvoutHandle.open("DWT.hdltvout.dat");
}

DWT::~DWT() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete data_in_U;
    delete filter_g_U;
    delete filter_h_U;
    delete data_input_U;
    delete data_store_U;
    delete data_output_U;
    delete DWT_fadd_32ns_32nbkb_U1;
    delete DWT_fadd_32ns_32nbkb_U2;
    delete DWT_fmul_32ns_32ncud_U3;
    delete DWT_fmul_32ns_32ncud_U4;
}

void DWT::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void DWT::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_713_p2.read(), ap_const_lv1_1))) {
        cal_length_reg_465 = ap_const_lv32_400;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, exitcond3_fu_1114_p2.read()))) {
        cal_length_reg_465 = i_7_reg_1303.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_2_fu_707_p2.read()))) {
        i1_reg_443 = ap_const_lv11_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        i1_reg_443 = i_1_reg_1216.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        i2_reg_499 = i_2_reg_1391.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_12_fu_828_p2.read()))) {
        i2_reg_499 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_22_fu_972_p2.read()))) {
        i3_reg_511 = i_7_reg_1303.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_fu_1011_p2.read()))) {
        i3_reg_511 = i_3_fu_1022_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_1011_p2.read()))) {
        i4_reg_520 = ap_const_lv31_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        i4_reg_520 = i_4_reg_1412.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_40_fu_1032_p2.read()))) {
        i5_reg_531 = i_7_reg_1303.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp5_fu_1088_p2.read()))) {
        i5_reg_531 = i_5_fu_1108_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp5_fu_1088_p2.read()))) {
        i6_reg_540 = ap_const_lv11_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_1114_p2.read()))) {
        i6_reg_540 = i_6_fu_1120_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        if (esl_seteq<1,1,1>(ap_condition_453.read(), ap_const_boolean_1)) {
            i_load_1_reg_551 = i.read();
        } else if (esl_seteq<1,1,1>(ap_condition_178.read(), ap_const_boolean_1)) {
            i_load_1_reg_551 = tmp_18_fu_816_p2.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_6_fu_653_p2.read()))) {
        invdar1_reg_409 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_9_fu_684_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_s_fu_690_p2.read()))) {
        invdar1_reg_409 = indvarinc1_reg_1189.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_fu_684_p2.read()))) {
        invdar2_reg_421 = indvarinc2_fu_665_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        invdar2_reg_421 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_9_fu_684_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_fu_690_p2.read()))) {
        invdar3_reg_432 = ap_const_lv11_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_707_p2.read()))) {
        invdar3_reg_432 = indvarinc3_fu_696_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, cal_flag_load_load_fu_587_p1.read()) && 
         esl_seteq<1,1,1>(tmp_3_i_fu_620_p2.read(), ap_const_lv1_1))) {
        invdar_reg_398 = ap_const_lv11_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_653_p2.read()))) {
        invdar_reg_398 = indvarinc_fu_642_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        if (esl_seteq<1,1,1>(ap_condition_453.read(), ap_const_boolean_1)) {
            j_load_2_reg_560 = j.read();
        } else if (esl_seteq<1,1,1>(ap_condition_178.read(), ap_const_boolean_1)) {
            j_load_2_reg_560 = ap_const_lv32_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        k_reg_488 = k_1_reg_1319.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_828_p2.read()))) {
        k_reg_488 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_713_p2.read(), ap_const_lv1_1))) {
        level_reg_454 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, exitcond3_fu_1114_p2.read()))) {
        level_reg_454 = level_1_reg_1234.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, cal_flag_load_reg_1170.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_730_p2.read()))) {
        n_reg_477 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_29_fu_937_p2.read()) || 
                 esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_fu_926_p2.read())))) {
        n_reg_477 = n_1_reg_1282.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && (esl_seteq<1,1,1>(exitcond4_fu_730_p2.read(), ap_const_lv1_1) || 
  esl_seteq<1,1,1>(cal_flag_load_reg_1170.read(), ap_const_lv1_1)))) {
        cal_flag = ap_const_lv1_1;
        tmp_11_reg_1262 = tmp_11_fu_800_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        cal_flag_load_reg_1170 = cal_flag.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_0, cal_flag_load_load_fu_587_p1.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_i_fu_591_p2.read()))) {
        cnt = tmp_1_i_fu_602_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        data_input_load_reg_1342 = data_input_q0.read();
        filter_g_load_reg_1348 = filter_g_q0.read();
        filter_h_load_reg_1353 = filter_h_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_828_p2.read()))) {
        data_output_addr_1_reg_1293 =  (sc_lv<14>) (tmp_54_cast_fu_859_p1.read());
        data_store_addr_1_reg_1298 =  (sc_lv<11>) (tmp_17_fu_845_p1.read());
        tmp_42_reg_1287 = tmp_42_fu_839_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        data_output_load_1_reg_1373 = data_output_q0.read();
        data_store_load_1_reg_1363 = data_store_q0.read();
        tmp_34_reg_1358 = grp_fu_579_p2.read();
        tmp_37_reg_1368 = grp_fu_583_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && ((esl_seteq<1,1,1>(exitcond4_fu_730_p2.read(), ap_const_lv1_1) && 
   esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_800_p2.read()) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, tmp_13_fu_810_p2.read())) || 
  (esl_seteq<1,1,1>(cal_flag_load_reg_1170.read(), ap_const_lv1_1) && 
   esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_800_p2.read()) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, tmp_13_fu_810_p2.read()))))) {
        i = tmp_18_fu_816_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_1_reg_1216 = i_1_fu_719_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        i_2_reg_1391 = i_2_fu_977_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        i_4_reg_1412 = i_4_fu_1037_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_12_fu_828_p2.read()))) {
        i_7_reg_1303 = i_7_fu_912_p3.read();
        tmp_14_reg_1310 = tmp_14_fu_920_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        indvarinc1_reg_1189 = indvarinc1_fu_659_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        j = tmp_21_fu_1158_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        k_1_reg_1319 = k_1_fu_931_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, cal_flag_load_reg_1170.read()))) {
        level_1_reg_1234 = level_1_fu_736_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        n_1_reg_1282 = n_1_fu_833_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, cal_flag_load_reg_1170.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_730_p2.read()))) {
        tmp_16_reg_1244 = tmp_16_fu_772_p2.read();
        tmp_4_reg_1239 = tmp_4_fu_742_p2.read();
        tmp_50_cast_reg_1249 = tmp_50_cast_fu_786_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        tmp_35_reg_1378 = grp_fu_571_p2.read();
        tmp_38_reg_1383 = grp_fu_575_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_0, cal_flag_load_load_fu_587_p1.read()))) {
        tmp_3_i_reg_1177 = tmp_3_i_fu_620_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_713_p2.read()))) {
        tmp_3_reg_1221 = tmp_3_fu_725_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_40_fu_1032_p2.read()))) {
        tmp_55_reg_1422 = tmp_55_fu_1065_p1.read();
    }
}

void DWT::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void DWT::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void DWT::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void DWT::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void DWT::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void DWT::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void DWT::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void DWT::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void DWT::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void DWT::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void DWT::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void DWT::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void DWT::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void DWT::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void DWT::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void DWT::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void DWT::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void DWT::thread_ap_CS_fsm_state27() {
    ap_CS_fsm_state27 = ap_CS_fsm.read()[26];
}

void DWT::thread_ap_CS_fsm_state28() {
    ap_CS_fsm_state28 = ap_CS_fsm.read()[27];
}

void DWT::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void DWT::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void DWT::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void DWT::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void DWT::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void DWT::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void DWT::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void DWT::thread_ap_condition_178() {
    ap_condition_178 = ((esl_seteq<1,1,1>(exitcond4_fu_730_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_800_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, tmp_13_fu_810_p2.read())) || (esl_seteq<1,1,1>(cal_flag_load_reg_1170.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_800_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, tmp_13_fu_810_p2.read())));
}

void DWT::thread_ap_condition_453() {
    ap_condition_453 = ((esl_seteq<1,1,1>(exitcond4_fu_730_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_800_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_fu_810_p2.read())) || (esl_seteq<1,1,1>(cal_flag_load_reg_1170.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_800_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_fu_810_p2.read())));
}

void DWT::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void DWT::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void DWT::thread_ap_phi_mux_cnt_loc_i_phi_fu_381_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, cal_flag_load_load_fu_587_p1.read()))) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_591_p2.read())) {
            ap_phi_mux_cnt_loc_i_phi_fu_381_p4 = cnt.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_i_fu_591_p2.read())) {
            ap_phi_mux_cnt_loc_i_phi_fu_381_p4 = tmp_1_i_fu_602_p2.read();
        } else {
            ap_phi_mux_cnt_loc_i_phi_fu_381_p4 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        ap_phi_mux_cnt_loc_i_phi_fu_381_p4 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void DWT::thread_ap_phi_mux_read_ready_i_phi_fu_390_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, cal_flag_load_load_fu_587_p1.read()))) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_591_p2.read())) {
            ap_phi_mux_read_ready_i_phi_fu_390_p4 = ap_const_lv1_0;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_i_fu_591_p2.read())) {
            ap_phi_mux_read_ready_i_phi_fu_390_p4 = ap_const_lv1_1;
        } else {
            ap_phi_mux_read_ready_i_phi_fu_390_p4 =  (sc_lv<1>) ("X");
        }
    } else {
        ap_phi_mux_read_ready_i_phi_fu_390_p4 =  (sc_lv<1>) ("X");
    }
}

void DWT::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void DWT::thread_cal_flag_load_load_fu_587_p1() {
    cal_flag_load_load_fu_587_p1 = cal_flag.read();
}

void DWT::thread_data_in_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        data_in_address0 =  (sc_lv<12>) (tmp_3_fu_725_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        data_in_address0 =  (sc_lv<12>) (tmp_2_i_fu_615_p1.read());
    } else {
        data_in_address0 =  (sc_lv<12>) ("XXXXXXXXXXXX");
    }
}

void DWT::thread_data_in_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        data_in_ce0 = ap_const_logic_1;
    } else {
        data_in_ce0 = ap_const_logic_0;
    }
}

void DWT::thread_data_in_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, cal_flag_load_load_fu_587_p1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_i_fu_591_p2.read()))) {
        data_in_we0 = ap_const_logic_1;
    } else {
        data_in_we0 = ap_const_logic_0;
    }
}

void DWT::thread_data_input_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        data_input_address0 =  (sc_lv<11>) (tmp_36_fu_1017_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        data_input_address0 =  (sc_lv<11>) (tmp_27_fu_996_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        data_input_address0 =  (sc_lv<11>) (tmp_32_fu_948_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        data_input_address0 =  (sc_lv<11>) (tmp_3_reg_1221.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        data_input_address0 =  (sc_lv<11>) (tmp_1_fu_702_p1.read());
    } else {
        data_input_address0 =  (sc_lv<11>) ("XXXXXXXXXXX");
    }
}

void DWT::thread_data_input_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()))) {
        data_input_ce0 = ap_const_logic_1;
    } else {
        data_input_ce0 = ap_const_logic_0;
    }
}

void DWT::thread_data_input_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        data_input_d0 = data_store_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        data_input_d0 = data_in_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()))) {
        data_input_d0 = ap_const_lv32_0;
    } else {
        data_input_d0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void DWT::thread_data_input_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_fu_1011_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()))) {
        data_input_we0 = ap_const_logic_1;
    } else {
        data_input_we0 = ap_const_logic_0;
    }
}

void DWT::thread_data_out() {
    data_out = data_output_q0.read();
}

void DWT::thread_data_out_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()) && 
         ((esl_seteq<1,1,1>(tmp_3_i_reg_1177.read(), ap_const_lv1_1) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_reg_1262.read())) || 
          (esl_seteq<1,1,1>(cal_flag_load_reg_1170.read(), ap_const_lv1_1) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_reg_1262.read()))))) {
        data_out_ap_vld = ap_const_logic_1;
    } else {
        data_out_ap_vld = ap_const_logic_0;
    }
}

void DWT::thread_data_output_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        data_output_address0 =  (sc_lv<14>) (tmp_57_cast_fu_1153_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        data_output_address0 =  (sc_lv<14>) (tmp_61_cast_fu_1103_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        data_output_address0 =  (sc_lv<14>) (tmp_60_cast_fu_1073_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        data_output_address0 =  (sc_lv<14>) (tmp_59_cast_fu_1060_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        data_output_address0 = data_output_addr_1_reg_1293.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        data_output_address0 =  (sc_lv<14>) (tmp_7_fu_679_p1.read());
    } else {
        data_output_address0 =  (sc_lv<14>) ("XXXXXXXXXXXXXX");
    }
}

void DWT::thread_data_output_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        data_output_ce0 = ap_const_logic_1;
    } else {
        data_output_ce0 = ap_const_logic_0;
    }
}

void DWT::thread_data_output_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        data_output_d0 = data_output_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        data_output_d0 = tmp_38_reg_1383.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read()))) {
        data_output_d0 = ap_const_lv32_0;
    } else {
        data_output_d0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void DWT::thread_data_output_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp5_fu_1088_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()))) {
        data_output_we0 = ap_const_logic_1;
    } else {
        data_output_we0 = ap_const_logic_0;
    }
}

void DWT::thread_data_store_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        data_store_address0 =  (sc_lv<11>) (tmp_48_fu_1126_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        data_store_address0 =  (sc_lv<11>) (tmp_26_fu_991_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        data_store_address0 = data_store_addr_1_reg_1298.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_store_address0 =  (sc_lv<11>) (tmp_5_fu_648_p1.read());
    } else {
        data_store_address0 =  (sc_lv<11>) ("XXXXXXXXXXX");
    }
}

void DWT::thread_data_store_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        data_store_ce0 = ap_const_logic_1;
    } else {
        data_store_ce0 = ap_const_logic_0;
    }
}

void DWT::thread_data_store_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        data_store_d0 = tmp_35_reg_1378.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()))) {
        data_store_d0 = ap_const_lv32_0;
    } else {
        data_store_d0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void DWT::thread_data_store_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_1114_p2.read())))) {
        data_store_we0 = ap_const_logic_1;
    } else {
        data_store_we0 = ap_const_logic_0;
    }
}

void DWT::thread_exitcond3_fu_1114_p2() {
    exitcond3_fu_1114_p2 = (!i6_reg_540.read().is_01() || !ap_const_lv11_400.is_01())? sc_lv<1>(): sc_lv<1>(i6_reg_540.read() == ap_const_lv11_400);
}

void DWT::thread_exitcond4_fu_730_p2() {
    exitcond4_fu_730_p2 = (!level_reg_454.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(level_reg_454.read() == ap_const_lv3_5);
}

void DWT::thread_exitcond5_fu_713_p2() {
    exitcond5_fu_713_p2 = (!i1_reg_443.read().is_01() || !ap_const_lv11_400.is_01())? sc_lv<1>(): sc_lv<1>(i1_reg_443.read() == ap_const_lv11_400);
}

void DWT::thread_filter_g_address0() {
    filter_g_address0 =  (sc_lv<6>) (tmp_58_cast_fu_962_p1.read());
}

void DWT::thread_filter_g_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        filter_g_ce0 = ap_const_logic_1;
    } else {
        filter_g_ce0 = ap_const_logic_0;
    }
}

void DWT::thread_filter_h_address0() {
    filter_h_address0 =  (sc_lv<6>) (tmp_58_cast_fu_962_p1.read());
}

void DWT::thread_filter_h_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        filter_h_ce0 = ap_const_logic_1;
    } else {
        filter_h_ce0 = ap_const_logic_0;
    }
}

void DWT::thread_i2_cast_fu_968_p1() {
    i2_cast_fu_968_p1 = esl_zext<32,31>(i2_reg_499.read());
}

void DWT::thread_i4_cast_fu_1028_p1() {
    i4_cast_fu_1028_p1 = esl_zext<32,31>(i4_reg_520.read());
}

void DWT::thread_i_1_fu_719_p2() {
    i_1_fu_719_p2 = (!i1_reg_443.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(i1_reg_443.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void DWT::thread_i_2_fu_977_p2() {
    i_2_fu_977_p2 = (!i2_reg_499.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(i2_reg_499.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void DWT::thread_i_3_fu_1022_p2() {
    i_3_fu_1022_p2 = (!i3_reg_511.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(i3_reg_511.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void DWT::thread_i_4_fu_1037_p2() {
    i_4_fu_1037_p2 = (!i4_reg_520.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(i4_reg_520.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void DWT::thread_i_5_fu_1108_p2() {
    i_5_fu_1108_p2 = (!ap_const_lv32_1.is_01() || !i5_reg_531.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(i5_reg_531.read()));
}

void DWT::thread_i_6_fu_1120_p2() {
    i_6_fu_1120_p2 = (!i6_reg_540.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(i6_reg_540.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void DWT::thread_i_7_fu_912_p3() {
    i_7_fu_912_p3 = (!tmp_20_fu_864_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_20_fu_864_p3.read()[0].to_bool())? p_neg_t_fu_892_p2.read(): tmp_33_fu_908_p1.read());
}

void DWT::thread_icmp5_fu_1088_p2() {
    icmp5_fu_1088_p2 = (!tmp_57_fu_1078_p4.read().is_01() || !ap_const_lv22_1.is_01())? sc_lv<1>(): (sc_bigint<22>(tmp_57_fu_1078_p4.read()) < sc_bigint<22>(ap_const_lv22_1));
}

void DWT::thread_icmp_fu_1011_p2() {
    icmp_fu_1011_p2 = (!tmp_50_fu_1001_p4.read().is_01() || !ap_const_lv22_1.is_01())? sc_lv<1>(): (sc_bigint<22>(tmp_50_fu_1001_p4.read()) < sc_bigint<22>(ap_const_lv22_1));
}

void DWT::thread_indvarinc1_fu_659_p2() {
    indvarinc1_fu_659_p2 = (!invdar1_reg_409.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(invdar1_reg_409.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void DWT::thread_indvarinc2_fu_665_p2() {
    indvarinc2_fu_665_p2 = (!invdar2_reg_421.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(invdar2_reg_421.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void DWT::thread_indvarinc3_fu_696_p2() {
    indvarinc3_fu_696_p2 = (!invdar3_reg_432.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(invdar3_reg_432.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void DWT::thread_indvarinc_fu_642_p2() {
    indvarinc_fu_642_p2 = (!invdar_reg_398.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(invdar_reg_398.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void DWT::thread_k_1_fu_931_p2() {
    k_1_fu_931_p2 = (!k_reg_488.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(k_reg_488.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void DWT::thread_level_1_fu_736_p2() {
    level_1_fu_736_p2 = (!level_reg_454.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(level_reg_454.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void DWT::thread_n_1_fu_833_p2() {
    n_1_fu_833_p2 = (!n_reg_477.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(n_reg_477.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void DWT::thread_p_lshr_f_fu_898_p4() {
    p_lshr_f_fu_898_p4 = cal_length_reg_465.read().range(31, 1);
}

void DWT::thread_p_lshr_fu_878_p4() {
    p_lshr_fu_878_p4 = p_neg_fu_872_p2.read().range(31, 1);
}

void DWT::thread_p_neg_fu_872_p2() {
    p_neg_fu_872_p2 = (!ap_const_lv32_0.is_01() || !cal_length_reg_465.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(cal_length_reg_465.read()));
}

void DWT::thread_p_neg_t_fu_892_p2() {
    p_neg_t_fu_892_p2 = (!ap_const_lv32_0.is_01() || !tmp_30_fu_888_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(tmp_30_fu_888_p1.read()));
}

void DWT::thread_p_shl1_cast_fu_768_p1() {
    p_shl1_cast_fu_768_p1 = esl_zext<7,4>(tmp_10_fu_760_p3.read());
}

void DWT::thread_p_shl_cast_fu_756_p1() {
    p_shl_cast_fu_756_p1 = esl_zext<7,6>(tmp_8_fu_748_p3.read());
}

void DWT::thread_read_over() {
    read_over = esl_zext<32,1>(tmp_3_i_fu_620_p2.read());
}

void DWT::thread_read_over_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, cal_flag_load_load_fu_587_p1.read()))) {
        read_over_ap_vld = ap_const_logic_1;
    } else {
        read_over_ap_vld = ap_const_logic_0;
    }
}

void DWT::thread_read_ready() {
    read_ready = esl_zext<32,1>(read_ready_write_ass_fu_626_p2.read());
}

void DWT::thread_read_ready_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, cal_flag_load_load_fu_587_p1.read()))) {
        read_ready_ap_vld = ap_const_logic_1;
    } else {
        read_ready_ap_vld = ap_const_logic_0;
    }
}

void DWT::thread_read_ready_write_ass_fu_626_p2() {
    read_ready_write_ass_fu_626_p2 = (tmp_3_i_fu_620_p2.read() | ap_phi_mux_read_ready_i_phi_fu_390_p4.read());
}

void DWT::thread_tmp_10_fu_760_p3() {
    tmp_10_fu_760_p3 = esl_concat<3,1>(level_reg_454.read(), ap_const_lv1_0);
}

void DWT::thread_tmp_11_fu_800_p2() {
    tmp_11_fu_800_p2 = (!i.read().is_01() || !ap_const_lv32_5.is_01())? sc_lv<1>(): sc_lv<1>(i.read() == ap_const_lv32_5);
}

void DWT::thread_tmp_12_fu_828_p2() {
    tmp_12_fu_828_p2 = (!n_reg_477.read().is_01() || !tmp_4_reg_1239.read().is_01())? sc_lv<1>(): (sc_bigint<32>(n_reg_477.read()) > sc_bigint<32>(tmp_4_reg_1239.read()));
}

void DWT::thread_tmp_13_fu_810_p2() {
    tmp_13_fu_810_p2 = (!j.read().is_01() || !ap_const_lv32_400.is_01())? sc_lv<1>(): sc_lv<1>(j.read() == ap_const_lv32_400);
}

void DWT::thread_tmp_14_fu_920_p2() {
    tmp_14_fu_920_p2 = (!i_7_fu_912_p3.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(i_7_fu_912_p3.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void DWT::thread_tmp_16_fu_772_p2() {
    tmp_16_fu_772_p2 = (!p_shl1_cast_fu_768_p1.read().is_01() || !p_shl_cast_fu_756_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(p_shl1_cast_fu_768_p1.read()) + sc_biguint<7>(p_shl_cast_fu_756_p1.read()));
}

void DWT::thread_tmp_17_fu_845_p1() {
    tmp_17_fu_845_p1 = esl_sext<64,32>(n_reg_477.read());
}

void DWT::thread_tmp_18_fu_816_p2() {
    tmp_18_fu_816_p2 = (!i.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(i.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void DWT::thread_tmp_19_fu_778_p3() {
    tmp_19_fu_778_p3 = esl_concat<3,11>(level_reg_454.read(), ap_const_lv11_0);
}

void DWT::thread_tmp_1_fu_702_p1() {
    tmp_1_fu_702_p1 = esl_zext<64,11>(invdar3_reg_432.read());
}

void DWT::thread_tmp_1_i_fu_602_p0() {
    tmp_1_i_fu_602_p0 = cnt.read();
}

void DWT::thread_tmp_1_i_fu_602_p2() {
    tmp_1_i_fu_602_p2 = (!tmp_1_i_fu_602_p0.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_1_i_fu_602_p0.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void DWT::thread_tmp_20_fu_864_p3() {
    tmp_20_fu_864_p3 = cal_length_reg_465.read().range(31, 31);
}

void DWT::thread_tmp_21_fu_1158_p2() {
    tmp_21_fu_1158_p2 = (!ap_const_lv32_1.is_01() || !j_load_2_reg_560.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(j_load_2_reg_560.read()));
}

void DWT::thread_tmp_22_fu_972_p2() {
    tmp_22_fu_972_p2 = (!i2_cast_fu_968_p1.read().is_01() || !tmp_14_reg_1310.read().is_01())? sc_lv<1>(): (sc_bigint<32>(i2_cast_fu_968_p1.read()) > sc_bigint<32>(tmp_14_reg_1310.read()));
}

void DWT::thread_tmp_23_fu_926_p2() {
    tmp_23_fu_926_p2 = (!k_reg_488.read().is_01() || !tmp_42_reg_1287.read().is_01())? sc_lv<1>(): (sc_bigint<32>(k_reg_488.read()) > sc_bigint<32>(tmp_42_reg_1287.read()));
}

void DWT::thread_tmp_25_fu_983_p3() {
    tmp_25_fu_983_p3 = esl_concat<31,1>(i2_reg_499.read(), ap_const_lv1_0);
}

void DWT::thread_tmp_26_fu_991_p1() {
    tmp_26_fu_991_p1 = esl_zext<64,32>(tmp_25_fu_983_p3.read());
}

void DWT::thread_tmp_27_fu_996_p1() {
    tmp_27_fu_996_p1 = esl_zext<64,31>(i2_reg_499.read());
}

void DWT::thread_tmp_29_fu_937_p2() {
    tmp_29_fu_937_p2 = (!k_reg_488.read().is_01() || !ap_const_lv32_9.is_01())? sc_lv<1>(): (sc_bigint<32>(k_reg_488.read()) > sc_bigint<32>(ap_const_lv32_9));
}

void DWT::thread_tmp_2_fu_707_p2() {
    tmp_2_fu_707_p2 = (!invdar3_reg_432.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(invdar3_reg_432.read() == ap_const_lv11_7FF);
}

void DWT::thread_tmp_2_i_fu_615_p0() {
    tmp_2_i_fu_615_p0 = cnt.read();
}

void DWT::thread_tmp_2_i_fu_615_p1() {
    tmp_2_i_fu_615_p1 = esl_sext<64,32>(tmp_2_i_fu_615_p0.read());
}

void DWT::thread_tmp_30_fu_888_p1() {
    tmp_30_fu_888_p1 = esl_zext<32,31>(p_lshr_fu_878_p4.read());
}

void DWT::thread_tmp_31_fu_943_p2() {
    tmp_31_fu_943_p2 = (!tmp_42_reg_1287.read().is_01() || !k_reg_488.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_42_reg_1287.read()) - sc_biguint<32>(k_reg_488.read()));
}

void DWT::thread_tmp_32_fu_948_p1() {
    tmp_32_fu_948_p1 = esl_sext<64,32>(tmp_31_fu_943_p2.read());
}

void DWT::thread_tmp_33_fu_908_p1() {
    tmp_33_fu_908_p1 = esl_zext<32,31>(p_lshr_f_fu_898_p4.read());
}

void DWT::thread_tmp_36_fu_1017_p1() {
    tmp_36_fu_1017_p1 = esl_sext<64,32>(i3_reg_511.read());
}

void DWT::thread_tmp_3_fu_725_p1() {
    tmp_3_fu_725_p1 = esl_zext<64,11>(i1_reg_443.read());
}

void DWT::thread_tmp_3_i_fu_620_p2() {
    tmp_3_i_fu_620_p2 = (!ap_phi_mux_cnt_loc_i_phi_fu_381_p4.read().is_01() || !ap_const_lv32_400.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_cnt_loc_i_phi_fu_381_p4.read() == ap_const_lv32_400);
}

void DWT::thread_tmp_40_fu_1032_p2() {
    tmp_40_fu_1032_p2 = (!i4_cast_fu_1028_p1.read().is_01() || !tmp_14_reg_1310.read().is_01())? sc_lv<1>(): (sc_bigint<32>(i4_cast_fu_1028_p1.read()) > sc_bigint<32>(tmp_14_reg_1310.read()));
}

void DWT::thread_tmp_42_fu_839_p2() {
    tmp_42_fu_839_p2 = (!ap_const_lv32_1.is_01())? sc_lv<32>(): n_reg_477.read() << (unsigned short)ap_const_lv32_1.to_uint();
}

void DWT::thread_tmp_43_cast_fu_1047_p3() {
    tmp_43_cast_fu_1047_p3 = esl_concat<14,1>(tmp_53_fu_1043_p1.read(), ap_const_lv1_0);
}

void DWT::thread_tmp_43_fu_850_p1() {
    tmp_43_fu_850_p1 = n_reg_477.read().range(15-1, 0);
}

void DWT::thread_tmp_44_fu_854_p2() {
    tmp_44_fu_854_p2 = (!tmp_43_fu_850_p1.read().is_01() || !tmp_50_cast_reg_1249.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_43_fu_850_p1.read()) + sc_biguint<15>(tmp_50_cast_reg_1249.read()));
}

void DWT::thread_tmp_45_fu_1131_p1() {
    tmp_45_fu_1131_p1 = j_load_2_reg_560.read().range(15-1, 0);
}

void DWT::thread_tmp_47_fu_1135_p1() {
    tmp_47_fu_1135_p1 = i_load_1_reg_551.read().range(4-1, 0);
}

void DWT::thread_tmp_48_fu_1126_p1() {
    tmp_48_fu_1126_p1 = esl_zext<64,11>(i6_reg_540.read());
}

void DWT::thread_tmp_49_fu_1147_p2() {
    tmp_49_fu_1147_p2 = (!tmp_56_cast_fu_1139_p3.read().is_01() || !tmp_45_fu_1131_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_56_cast_fu_1139_p3.read()) + sc_biguint<15>(tmp_45_fu_1131_p1.read()));
}

void DWT::thread_tmp_4_fu_742_p2() {
    tmp_4_fu_742_p2 = (!cal_length_reg_465.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(cal_length_reg_465.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void DWT::thread_tmp_50_cast_fu_786_p1() {
    tmp_50_cast_fu_786_p1 = esl_zext<15,14>(tmp_19_fu_778_p3.read());
}

void DWT::thread_tmp_50_fu_1001_p4() {
    tmp_50_fu_1001_p4 = i3_reg_511.read().range(31, 10);
}

void DWT::thread_tmp_51_fu_953_p1() {
    tmp_51_fu_953_p1 = k_reg_488.read().range(7-1, 0);
}

void DWT::thread_tmp_52_fu_957_p2() {
    tmp_52_fu_957_p2 = (!tmp_16_reg_1244.read().is_01() || !tmp_51_fu_953_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_16_reg_1244.read()) + sc_biguint<7>(tmp_51_fu_953_p1.read()));
}

void DWT::thread_tmp_53_fu_1043_p1() {
    tmp_53_fu_1043_p1 = i4_reg_520.read().range(14-1, 0);
}

void DWT::thread_tmp_54_cast_fu_859_p1() {
    tmp_54_cast_fu_859_p1 = esl_sext<64,15>(tmp_44_fu_854_p2.read());
}

void DWT::thread_tmp_54_fu_1055_p2() {
    tmp_54_fu_1055_p2 = (!tmp_50_cast_reg_1249.read().is_01() || !tmp_43_cast_fu_1047_p3.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_50_cast_reg_1249.read()) + sc_biguint<15>(tmp_43_cast_fu_1047_p3.read()));
}

void DWT::thread_tmp_55_fu_1065_p1() {
    tmp_55_fu_1065_p1 = i4_reg_520.read().range(15-1, 0);
}

void DWT::thread_tmp_56_cast_fu_1139_p3() {
    tmp_56_cast_fu_1139_p3 = esl_concat<4,11>(tmp_47_fu_1135_p1.read(), ap_const_lv11_0);
}

void DWT::thread_tmp_56_fu_1069_p2() {
    tmp_56_fu_1069_p2 = (!tmp_50_cast_reg_1249.read().is_01() || !tmp_55_reg_1422.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_50_cast_reg_1249.read()) + sc_biguint<15>(tmp_55_reg_1422.read()));
}

void DWT::thread_tmp_57_cast_fu_1153_p1() {
    tmp_57_cast_fu_1153_p1 = esl_sext<64,15>(tmp_49_fu_1147_p2.read());
}

void DWT::thread_tmp_57_fu_1078_p4() {
    tmp_57_fu_1078_p4 = i5_reg_531.read().range(31, 10);
}

void DWT::thread_tmp_58_cast_fu_962_p1() {
    tmp_58_cast_fu_962_p1 = esl_sext<64,7>(tmp_52_fu_957_p2.read());
}

void DWT::thread_tmp_58_fu_1094_p1() {
    tmp_58_fu_1094_p1 = i5_reg_531.read().range(15-1, 0);
}

void DWT::thread_tmp_59_cast_fu_1060_p1() {
    tmp_59_cast_fu_1060_p1 = esl_zext<64,15>(tmp_54_fu_1055_p2.read());
}

void DWT::thread_tmp_59_fu_1098_p2() {
    tmp_59_fu_1098_p2 = (!tmp_50_cast_reg_1249.read().is_01() || !tmp_58_fu_1094_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_50_cast_reg_1249.read()) + sc_biguint<15>(tmp_58_fu_1094_p1.read()));
}

void DWT::thread_tmp_5_fu_648_p1() {
    tmp_5_fu_648_p1 = esl_zext<64,11>(invdar_reg_398.read());
}

void DWT::thread_tmp_60_cast_fu_1073_p1() {
    tmp_60_cast_fu_1073_p1 = esl_zext<64,15>(tmp_56_fu_1069_p2.read());
}

void DWT::thread_tmp_61_cast_fu_1103_p1() {
    tmp_61_cast_fu_1103_p1 = esl_sext<64,15>(tmp_59_fu_1098_p2.read());
}

void DWT::thread_tmp_6_fu_653_p2() {
    tmp_6_fu_653_p2 = (!invdar_reg_398.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(invdar_reg_398.read() == ap_const_lv11_7FF);
}

void DWT::thread_tmp_7_fu_679_p1() {
    tmp_7_fu_679_p1 = esl_zext<64,14>(tmp_fu_671_p3.read());
}

void DWT::thread_tmp_8_fu_748_p3() {
    tmp_8_fu_748_p3 = esl_concat<3,3>(level_reg_454.read(), ap_const_lv3_0);
}

void DWT::thread_tmp_9_fu_684_p2() {
    tmp_9_fu_684_p2 = (!invdar2_reg_421.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(invdar2_reg_421.read() == ap_const_lv11_7FF);
}

void DWT::thread_tmp_fu_671_p3() {
    tmp_fu_671_p3 = esl_concat<3,11>(invdar1_reg_409.read(), invdar2_reg_421.read());
}

void DWT::thread_tmp_i_fu_591_p2() {
    tmp_i_fu_591_p2 = (!read_valid.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<1>(): sc_lv<1>(read_valid.read() == ap_const_lv32_1);
}

void DWT::thread_tmp_s_fu_690_p2() {
    tmp_s_fu_690_p2 = (!invdar1_reg_409.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(invdar1_reg_409.read() == ap_const_lv3_4);
}

void DWT::thread_write_valid() {
    write_valid = ap_const_lv32_1;
}

void DWT::thread_write_valid_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()) && 
         ((esl_seteq<1,1,1>(tmp_3_i_reg_1177.read(), ap_const_lv1_1) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_reg_1262.read())) || 
          (esl_seteq<1,1,1>(cal_flag_load_reg_1170.read(), ap_const_lv1_1) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_reg_1262.read()))))) {
        write_valid_ap_vld = ap_const_logic_1;
    } else {
        write_valid_ap_vld = ap_const_logic_0;
    }
}

void DWT::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_0, cal_flag_load_load_fu_587_p1.read()) && esl_seteq<1,1,1>(tmp_3_i_fu_620_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_0, cal_flag_load_load_fu_587_p1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_i_fu_620_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state28;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(cal_flag_load_load_fu_587_p1.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_6_fu_653_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_9_fu_684_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_fu_690_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_9_fu_684_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_s_fu_690_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_2_fu_707_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(exitcond5_fu_713_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && ((esl_seteq<1,1,1>(exitcond4_fu_730_p2.read(), ap_const_lv1_1) && 
   esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_800_p2.read())) || 
  (esl_seteq<1,1,1>(cal_flag_load_reg_1170.read(), ap_const_lv1_1) && 
   esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_800_p2.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state27;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && ((esl_seteq<1,1,1>(exitcond4_fu_730_p2.read(), ap_const_lv1_1) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, tmp_11_fu_800_p2.read())) || 
  (esl_seteq<1,1,1>(cal_flag_load_reg_1170.read(), ap_const_lv1_1) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, tmp_11_fu_800_p2.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state28;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_12_fu_828_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state20;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_29_fu_937_p2.read()) || 
  esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_fu_926_p2.read())))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 524288 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_22_fu_972_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state22;
            } else {
                ap_NS_fsm = ap_ST_fsm_state21;
            }
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 2097152 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_1011_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state23;
            } else {
                ap_NS_fsm = ap_ST_fsm_state22;
            }
            break;
        case 4194304 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_40_fu_1032_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state25;
            } else {
                ap_NS_fsm = ap_ST_fsm_state24;
            }
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 16777216 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp5_fu_1088_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state26;
            } else {
                ap_NS_fsm = ap_ST_fsm_state25;
            }
            break;
        case 33554432 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond3_fu_1114_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state26;
            }
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<28>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void DWT::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"data_out\" :  \"" << data_out.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"data_out_ap_vld\" :  \"" << data_out_ap_vld.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"data\" :  \"" << data.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"read_valid\" :  \"" << read_valid.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"read_ready\" :  \"" << read_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"read_ready_ap_vld\" :  \"" << read_ready_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"read_over\" :  \"" << read_over.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"read_over_ap_vld\" :  \"" << read_over_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"write_valid\" :  \"" << write_valid.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"write_valid_ap_vld\" :  \"" << write_valid_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

